### PR TITLE
Add LIBXML_NOCDATA

### PR DESCRIPTION
**Pull request by jenssegers**
I'm having some issues parsing XML with CDATA. Adding this option converts the CDATA to string values.

### CODE REVIEW

**Comment by hobnob** [comment]
Hi @jenssegers ,

I've used this for a while now with Atom and RSS feeds that use CDATA without issue. Can you explain the problem you're seeing along with the PHP version and example?

**Comment by jenssegers** [comment]
It is mostly an issue when you want to cast the xml object to an array. Are there any downsides to not adding it?

**Comment by hobnob** [comment]
Not that I'm aware of, but I'll have to test it to make sure
As all the tests pass I find it unlikely to cause issue, but I'll have a play and let you know :)

**Comment by jenssegers** [comment]
Any news on this?

**Comment by hobnob** [comment]
Hi @jenssegers  , Sorry about the delay on this. I see no issue with it, so I'll merge it in now for you

**Comment by jenssegers** [comment]
Are you planning to tag a new release including this PR?

**Pull request merged**
