### PR TITLE
Allow registerCallback on array of paths

### PR DESCRIPTION
**Pull request by jenssegers**
This adds support for registering a callback to multiple paths.

### CODE REVIEW

**Comment by hobnob** [comment]
Hi @jenssegers , thanks for the PR :)

I think I'de prefer this to be in a seperate function called `registerCallbacks` so that $paths can be type hinted as an array

The logic is sound though, so just needs moving to a new function

Thanks again :)

**Comment by jenssegers** [comment]
There is already a function called `registerCallbacks`, but `registerCallback` made more sense to me as -you are registering a single callback to multiple tags.

**Comment by hobnob** [comment]
Appologies @jenssegers , it's been a while since I last looked at this and I'd forgotten about the `registerCallbacks` method

Ok.. let's add this functionality into `registerCallback` as it does seem to make sense.
Could you add a supporting unit test as well? Once that's done, I'll merge in this PR

Thanks!

**Comment by hobnob** [comment]
Hi @jenssegers , Could I get a small unit test for this change please? Once done I'll merge it in and get a release out with your changes :)

**Pull request closed without merging**
